AWSTemplateFormatVersion: "2010-09-09"

Description: Cloudformation Template for State Machine deployment
#Todo
Parameters:
 LambdaLayer:
   Default: DataRetrieveLayer
Resources:                 
 LambdaLayer:
   Type: AWS::Serverless::LayerVersion
   Properties:
     LayerName: !Ref LambdaLayer
     ContentUri: lambda-layer.zip
     CompatibleRuntimes:
       - python3.6
       - python3.7
      LicenseInfo: MIT
      RetentionPolicy: Retain