AWSTemplateFormatVersion: "2010-09-09"
Transform: 'AWS::Serverless-2016-10-31'
Description: Cloudformation Template for State Machine deployment
Parameters:
 LambdaLayerName:
   Type: String
   Default: DataRetrieveLayer
Resources:                 
 LambdaLayer:
   Type: AWS::Serverless::LayerVersion
   Properties:
     LayerName: !Ref LambdaLayerName
     ContentUri: s3://retreivedata-landing-lambda/lambda-layer.zip
     CompatibleRuntimes:
       - python3.6
       - python3.7
     LicenseInfo: MIT
     RetentionPolicy: Retain