AWSTemplateFormatVersion: 2010-09-09

Transform: 'AWS::Serverless-2016-10-31'
Description: Deploy Lambda code 
Parameters:
 SecurityGroups:
   Type: AWS::SSM::Parameter::Value<List<AWS::EC2::SecurityGroup::Id>>
   Default: /acs/private/deploy/common/securityGroups
 Subnets:
   Type: AWS::SSM::Parameter::Value<List<AWS::EC2::Subnet::Id>>
   Default: /acs/private/deploy/common/subnetGroups
 LambdaLayer:
   Default: DataRetrieveLayer
Resources:
 StartDataloadBatchFunction:
   Type: 'AWS::Serverless::Function'
   Properties:
     FunctionName: acs-start-dataload-batch-lambda
     Handler: acs-start-dataload-batch-lambda.lambda_handler
     Role: '{{resolve:ssm:/acs/lambda/vpcAccess/Arn}}'
     Runtime: python3.8
     Timeout: 30
     CodeUri:
         Bucket: '{{resolve:ssm:/acs/s3/lambda-landing/PrivateBucketName}}'
         Key: acs-start-dataload-batch.zip
     VpcConfig:
       SecurityGroupIds: !Ref SecurityGroups
       SubnetIds: !Ref Subnets
     Layers:
       - !Ref LambdaLayer      